name: Release PROD

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          # ℹ️ DEV NOTE: Using same repo for example only
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}        
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_IMAGE: "${{ steps.login-ecr.outputs.registry }}/myapp/api"
        run: |
          docker build -t $ECR_IMAGE:$GITHUB_REF_NAME .
          docker push $ECR_IMAGE:$GITHUB_REF_NAME